CREATE TABLE IF NOT EXISTS `notificacoes` (
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo` enum('aviso_geral','aviso_canteirista','evento_horta') COLLATE utf8mb4_unicode_ci NOT NULL,
  `titulo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mensagem` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `carteirista_uuid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'UUID do carteirista específico (apenas para tipo aviso_canteirista)',
  `horta_uuid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'UUID da horta relacionada ao evento',
  `data_evento` datetime DEFAULT NULL COMMENT 'Data do evento (apenas para tipo evento_horta)',
  `data_inicio` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Data de início da exibição',
  `data_fim` datetime DEFAULT NULL COMMENT 'Data de fim da exibição (NULL = sem prazo)',
  `ativa` tinyint NOT NULL DEFAULT '1' COMMENT '1 = ativa, 0 = inativa',
  `prioridade` enum('baixa','media','alta') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'media',
  `excluido` tinyint NOT NULL DEFAULT '0',
  `usuario_criador_uuid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_de_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_alterador_uuid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_de_ultima_alteracao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  KEY `idx_tipo` (`tipo`),
  KEY `idx_ativa` (`ativa`),
  KEY `idx_excluido` (`excluido`),
  KEY `idx_carteirista` (`carteirista_uuid`),
  KEY `idx_horta` (`horta_uuid`),
  KEY `idx_data_inicio` (`data_inicio`),
  KEY `idx_data_fim` (`data_fim`),
  CONSTRAINT `notificacoes_ibfk_1` FOREIGN KEY (`carteirista_uuid`) REFERENCES `carteiristas` (`uuid`),
  CONSTRAINT `notificacoes_ibfk_2` FOREIGN KEY (`horta_uuid`) REFERENCES `hortas` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabela de notificações e avisos para canteiristas';
